### ISSUE TITLE
Compile Sass

### ISSUE THREAD

**Issue by m-mcdonagh** [gevhaz/hugo-theme-notrack#5]
Hello,
I'm looking to change the colors in [static/css/styles.scss](https://github.com/gevhaz/hugo-theme-notrack/blob/master/static/css/styles.scss), and maybe make a PR if I can make it configurable. I compiled it with [npm's sass](https://www.npmjs.com/package/sass) `sass --no-source-map styles.scss styles.css` (from the static/css dir). The compiled output was identical, but without the newlines before the closing brace
Your file:
```css
nav li:hover {
  border-color: #ddd; }
```
My output:
```css
nav li:hover {
  border-color: #ddd;
}
```
How did you compile your scss files? I'm assuming it would not be good to submit a PR with a bunch of formatting changes, like my output would give me.
